version: '3'

services:
  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "ensimpl.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/app/ensimpl'
      - ${ENSIMPL_DATA}:/app/ensimpl/data
      - ${ENSIMPL_SETTINGS_LOCAL}:${ENSIMPL_SETTINGS}
    ports:
      - '${EXTERNAL_PORT}:8000'
